### ISSUE TITLE
Not finding branch name

### ISSUE THREAD

**Issue by IgorRebeche** [nemisj/git-removed-branches#9]
Hello, today i tried to prune my branches using your approach but when i tried to delete some error occurred as you can see in the screenshot
![image](https://user-images.githubusercontent.com/26829936/130686726-ba70a972-1275-4604-b274-72ec3d171672.png)

I think it can be a problem with the  deleteBranches implementation in find-stale.js.
It is using single quotes

i would change the line 256
```javascript
var exec = utils.asyncExec(['git', 'branch', dFlag, "'" + branchName + "'"]);
```

To
```javascript
var exec = utils.asyncExec(['git', 'branch', dFlag, branchName ]);
```
I am using windows, maybe in linux could work with single quote but i didn't test yet

**Comment by rhalaly** [comment]
I'm having the same issue. I want to add extra information:
If I get the error:
```
ERROR: Unable to remove: Command failed: git branch -D 'feature/add-button'
error: branch ''feature/add-button'' not found.
```

But if I run the exact same command (with the single quote) in the console manually, it works as expected:
```
 C:\Code\Project\*****> git branch -D 'feature/add-button'
 Deleted branch feature/add-button (was *****).
```

I'm running this on Windows

**Comment by erkage** [comment]
Hi,

I've made that change because of #6 in #8 . It works on macOS and Linux. I'll try to figure it out what's different on Windows and make a fix for it.

**Comment by nemisj** [comment]
1.0.5 should fix that @DerZyklop @IgorRebeche, can you please confirm?
@IgorRebeche, sorry for such a long answer, there is some issues with notifications to my email, haven't seen your message.

**Comment by rhalaly** [comment]
@nemisj I'm using 2.0.1 but unfortunately, it's still not working (on Windows)

![image](https://user-images.githubusercontent.com/8597700/141334122-9cf80f71-e8fe-48b6-9b89-470f3669a3fb.png)

![image](https://user-images.githubusercontent.com/8597700/141334022-fca4d64c-c28b-4f6e-a648-80545f7b1210.png)

**Comment by DerZyklop** [comment]
@rhalaly Thanks for reporting, but your issue is not related to this ticket. And it’s also not a bug. 

The message says "branch … is not fully merged". This means the branch exists, and the git-removed-branches command could find it, but It contains changes that have not been merged into your main branch yet.

✌

**Comment by rhalaly** [comment]
@DerZyklop it was a false alarm, indeed. Sorry!
